import "./globals.css";
import Header from "@/components/Header";
import Providers from "@/app/Providers";
import Tabs from "@/components/Tabs";
import Bars from "@/components/Bars";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          <Bars />
          {children}
        </Providers>
      </body>
    </html>
  );
}
